/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  mySidebar: [
    {
      type: 'doc',
      id: 'cloud3overview',
      label: 'Crust Cloud Overview'
    },
    {
      type: 'category',
      label: 'W3Bucket',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'w3bucket/aboutnft',
          label: 'About W3Bucket NFT'
        },
        {
          type: 'doc',
          id: 'w3bucket/nftmetadata',
          label: 'NFT Metadata'
        },
        {
          type: 'doc',
          id: 'w3bucket/uploadfile',
          label: 'Upload Files with API'
        },
      ]
    },
    {
      type: 'doc',
      id: 'w3auth',
      label: 'W3Auth'
    },
    {
      type: 'doc',
      id: 'toolkits',
      label: 'Crust Cloud Toolkits'
    }
  ]
};
